from .func_helper import delete_instance_on_error
